create table if not exists public.subject
(
    "id"               bigserial not null,
    "name"             text,
    "semester_type_id" bigint,
    "year_id"          bigint,
    primary key ("id"),
    unique ("name")
);
alter table public.subject
    owner to postgres;

create table if not exists public.year
(
    id   bigint generated by default as identity
        constraint year_pkey
            primary key,
    name varchar(255)
);
alter table public.year
    owner to postgres;

create table if not exists public.semester_type
(
    id   bigint generated by default as identity
        constraint semester_type_pkey
            primary key,
    name varchar(255)
);
alter table if exists public.semester_type
    owner to postgres;

create table if not exists public.exam_type
(
    id   bigint generated by default as identity
        constraint exam_type_pkey
            primary key,
    name varchar(255)
);
alter table public.exam_type
    owner to postgres;

create table if not exists auth_user.users
(
    "id"           bigserial not null,
    "email"        text,
    "password"     text,
    "date_created" timestamp with time zone,
    "role_id"      bigint,
    primary key ("id"),
    unique ("email")
);
alter table auth_user.users
    owner to postgres;

create table if not exists auth_user.user_roles
(
    "id"   bigserial not null,
    "name" text,
    primary key ("id"),
    unique ("name")
);
alter table auth_user.user_roles
    owner to postgres;

